# Generated by Django 3.1.4 on 2020-12-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('feature_image', models.ImageField(blank=True, upload_to='project_image')),
                ('architects', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('area', models.FloatField(default=0.0)),
                ('project_start', models.DateField(blank=True)),
                ('project_end', models.DateField(blank=True)),
                ('manufactures', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='project_image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_image', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_category', to='projects.projectcategory'),
        ),
    ]
