# Generated by Django 3.1.4 on 2020-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201202_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
