# Generated by Django 3.1.4 on 2020-12-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201204_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sub_title',
            field=models.TextField(blank=True),
        ),
    ]
