# Generated by Django 3.1.4 on 2020-12-02 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePageContent',
            new_name='Settings',
        ),
    ]
