# Generated by Django 3.1.4 on 2020-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='slider_image'),
        ),
    ]
