# Generated by Django 3.1.4 on 2020-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slider_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_subtitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
