# Generated by Django 3.1.4 on 2020-12-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201203_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
