# Generated by Django 3.1.7 on 2021-03-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='logo',
            new_name='footer_logo',
        ),
        migrations.AddField(
            model_name='settings',
            name='header_logo',
            field=models.ImageField(blank=True, upload_to='Logo'),
        ),
    ]
