# Generated by Django 3.1.7 on 2021-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210312_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='Logo'),
        ),
    ]
